# Generated by Django 6.0.4 on 2026-04-15 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionDialisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('peso_pre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_post', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ta_inicial', models.CharField(blank=True, max_length=20)),
                ('ta_final', models.CharField(blank=True, max_length=20)),
                ('medicacion', models.TextField(blank=True)),
                ('incidencias', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sesiones.puesto')),
            ],
            options={
                'ordering': ['-fecha', 'turno'],
            },
        ),
    ]
