# Generated by Django 6.0.4 on 2026-05-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0006_sesiondialisis_enfermero_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiondialisis',
            name='medico_asignado',
            field=models.CharField(blank=True, choices=[('juan_perez', 'Dr. Juan Pérez'), ('maria_garcia', 'Dra. María García'), ('roberto_lopez', 'Dr. Roberto López')], max_length=20, null=True),
        ),
    ]
