# Generated by Django 6.0.4 on 2026-05-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0010_alter_sesiondialisis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillahemodialisis',
            name='peso_post',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='peso_pre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='talla',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='frecuencia_cardiaca_final',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='frecuencia_cardiaca_inicial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='na',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='qb',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='qd',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='td',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='temperatura_final',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='temperatura_inicial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='uf_final',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
