# Generated by Django 6.0.4 on 2026-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='etiologia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ingreso_dialisis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
