# Generated by Django 6.0.4 on 2026-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondialisis',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'En sesión'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
