# Generated by Django 6.0.4 on 2026-04-27 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_sesiondialisis_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicaciones_medicas', models.TextField(blank=True)),
                ('eritropoyetina', models.CharField(blank=True, max_length=100)),
                ('hierro', models.CharField(blank=True, max_length=100)),
                ('vacunacion', models.CharField(blank=True, max_length=100)),
                ('antibiotico', models.CharField(blank=True, max_length=100)),
                ('paracetamol', models.CharField(blank=True, max_length=100)),
                ('otro', models.CharField(blank=True, max_length=100)),
                ('medicacion_entregada', models.TextField(blank=True)),
                ('evolucion_enfermeria', models.TextField(blank=True)),
                ('firma_medico', models.CharField(blank=True, max_length=100)),
                ('firma_enfermero', models.CharField(blank=True, max_length=100)),
                ('firma_paciente', models.CharField(blank=True, max_length=100)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sesiones.sesiondialisis')),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaHemodialisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_vascular', models.CharField(blank=True, max_length=100)),
                ('dializador', models.CharField(blank=True, max_length=100)),
                ('concentrado', models.CharField(blank=True, max_length=100)),
                ('talla', models.CharField(blank=True, max_length=50)),
                ('peso_seco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qb', models.IntegerField(blank=True, null=True)),
                ('peso_pre', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_post', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo', models.CharField(blank=True, max_length=50)),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=50)),
                ('heparina_inicial', models.CharField(blank=True, max_length=100)),
                ('heparina_hora', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sesiones.sesiondialisis')),
            ],
        ),
        migrations.CreateModel(
            name='ControlHorarioHemodialisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.PositiveIntegerField()),
                ('ta', models.CharField(blank=True, max_length=20)),
                ('pulso', models.CharField(blank=True, max_length=20)),
                ('qb', models.CharField(blank=True, max_length=20)),
                ('presion_venosa', models.CharField(blank=True, max_length=20)),
                ('ultrafiltracion', models.CharField(blank=True, max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='sesiones.planillahemodialisis')),
            ],
        ),
    ]
