# Generated by Django 6.0.4 on 2026-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0003_planillaenfermeria_planillahemodialisis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlhorariohemodialisis',
            options={'ordering': ['hora']},
        ),
        migrations.RenameField(
            model_name='planillahemodialisis',
            old_name='heparina_hora',
            new_name='agujas',
        ),
        migrations.RenameField(
            model_name='planillahemodialisis',
            old_name='frecuencia_cardiaca',
            new_name='frecuencia_cardiaca_final',
        ),
        migrations.RenameField(
            model_name='planillahemodialisis',
            old_name='tiempo',
            new_name='frecuencia_cardiaca_inicial',
        ),
        migrations.RemoveField(
            model_name='controlhorariohemodialisis',
            name='pulso',
        ),
        migrations.AddField(
            model_name='controlhorariohemodialisis',
            name='heparina_hora',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='atb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='na',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='qd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='ta_egreso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='ta_inicial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='td',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='temperatura_final',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='temperatura_inicial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='uf_final',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='uf_prescripta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='qb',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
