# Generated by Django 6.0.4 on 2026-05-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0004_alter_controlhorariohemodialisis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillahemodialisis',
            name='observaciones_enfermeria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='observaciones_medicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sesiondialisis',
            name='medico_asignado',
            field=models.CharField(blank=True, choices=[('medico1', 'Médico 1'), ('medico2', 'Médico 2'), ('medico3', 'Médico 3')], max_length=20, null=True),
        ),
    ]
