# Generated by Django 6.0.4 on 2026-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0005_planillahemodialisis_observaciones_enfermeria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiondialisis',
            name='enfermero_asignado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
