# Generated by Django 6.0.4 on 2026-05-27 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0007_alter_sesiondialisis_medico_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sesiondialisis',
            name='enfermero_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_enfermero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sesiondialisis',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sesiondialisis',
            name='turno',
            field=models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='manana', max_length=10),
        ),
    ]
