# Generated by Django 6.0.4 on 2026-05-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0008_alter_puesto_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesiondialisis',
            options={},
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='na',
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='qb',
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='qd',
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='td',
        ),
        migrations.RemoveField(
            model_name='sesiondialisis',
            name='incidencias',
        ),
        migrations.RemoveField(
            model_name='sesiondialisis',
            name='medicacion',
        ),
        migrations.RemoveField(
            model_name='sesiondialisis',
            name='observaciones',
        ),
        migrations.DeleteModel(
            name='PlanillaEnfermeria',
        ),
    ]
