# Generated by Django 6.0.4 on 2026-05-27 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0009_alter_sesiondialisis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesiondialisis',
            options={'ordering': ['-fecha', 'turno']},
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='peso_post',
        ),
        migrations.RemoveField(
            model_name='planillahemodialisis',
            name='peso_pre',
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='na',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='qb',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='qd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='planillahemodialisis',
            name='td',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='ta_egreso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='planillahemodialisis',
            name='ta_inicial',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
